### ISSUE TITLE
set_apt_conf is hardcoded to use web-proxy.corp.hpecorp.net

### ISSUE THREAD

**Issue by zvolchak** [FabricAttachedMemory/tm-manifesting#14]
Make a tmms config file entry something like "PROXY" and replace hardcoded values.

**Comment by coloroco** [comment]
I've already taken a step in that direction and we don't need a new /etc/tmms value.

The scripts will now "source" /etc/environment and use variables found there.   Some testing has been done to insure that much works, but the hard-coded values of web-proxy still need to be removed.

**Comment by zvolchak** [comment]
Yes, I'v been working on it today.
I'm actually thinking to move web_proxy variable to manifest instead of tmms.

**Comment by coloroco** [comment]
That would only help if you had specified a package via "http://somehwere....." and that particular URL needed a different proxy than the one set in /etc/environment.

**Comment by zvolchak** [comment]
Yeah that for starting the manifesting-server. But the enhancement needed here is for system image itself, isn't it? We don't want to set same host's proxy's to a custom sysimage. No?

**Comment by coloroco** [comment]
You need the proxy for creation of golden image and networking.   dnsmasq (PXE and DNS) will be started on the same server to serve the nodes, so essentially they're subject to the same restrictions as the host.

**Comment by coloroco** [comment]
There is a complication when using the l4fame-repo container to provide a true "localhost" repo for FAM(E) packages.  You need to override the proxy so it doesn't try to pass localhost.   I'll show you how I solved it on FAME.

**Comment by zvolchak** [comment]
Fixed after the following merges:
https://github.com/FabricAttachedMemory/tm-manifesting/pull/21
https://github.com/FabricAttachedMemory/tm-manifesting/pull/20
