### ISSUE TITLE
Try improve blueprints/10-package performance

### ISSUE THREAD

**Issue by zvolchak** [FabricAttachedMemory/tm-manifesting#3]
It takes 30+ seconds to read Packages.gz. Seems not that bad, but annoying when have to restart server constantly for debugging/testing purposes.

Potentially, it can be improved by half or so by "divide and conquered" approach to reading Packages.gz.

**Comment by zvolchak** [comment]
Had wrong assumption about where performance impact is.
Majority of the time is spent at the following line:
tmp = [ src for src in Packages.iter_paragraphs(unzipped) ]

Which is a "debian.deb822" library issue. This might take more time to figure out than it is worth for saving those 30 seconds of server boot time.

Mark as "wontfix". Maybe one day someone will figure this out just for fun.

**Comment by coloroco** [comment]
Well, it's downloaded and unpacking a 20M zip file, which expands to probably over 50M of TEXT, then parsing the text file.  30 seconds of Python execution is about as good as it's going to get.
